### ISSUE TITLE
AHTXX_START_MEASUREMENT_CTRL 

### ISSUE THREAD

**Issue by markusschweitzer** [enjoyneering/AHTxx#12]
Hi,
for me (in the default configuration) readTemperature() and readHumidity() takes ~ 80ms each.

I experimented a little bit with the AHTXX_START_MEASUREMENT_CTRL value. 0xFF seems to really speed up measurement.
How have you found the 0x33 value? It seems kind of undocumented...
Have you also tried to use other values here? 0xFF seems to work pretty well.

best regards

**Comment by enjoyneering** [comment]
Use the macro AHTXX_USE_READ_DATA on the second read. This saves time because the temperature reading is already in the library buffer after the humidity reading. Change this code to the code below.

```
    float humi1 = aht10.readHumidity(AHTXX_FORCE_READ_DATA); //AHTXX_FORCE_READ_DATA=read 6-bytes via I2C, takes 80 milliseconds
    float temp1 = aht10.readTemperature(AHTXX_USE_READ_DATA); //AHTXX_USE_READ_DATA=use 6-bytes from humidity reading, takes zero milliseconds!!!
```

The 0x33 is from AHT20 datasheet V1.0 from May 2021, AHT10 v1.2

![Screenshot 2022-11-03 071229](https://user-images.githubusercontent.com/10623649/199706843-65c9aa42-a31f-4735-bc09-940f0c349f8c.png)

![Screenshot 2022-11-03 071643](https://user-images.githubusercontent.com/10623649/199707577-63c7a21e-8fc6-4276-a36a-38db7275b9c2.png)
